version: '3'

services:
  mongo:
    image: mongo:4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  server:
    build: .
    ports:
      - '3001:3001'
    depends_on:
      - mongo
    environment:
      - PORT=${HTTP_PORT}
      - MONGO_URL=${MONGO_URL}
    volumes:
      - .env:/usr/src/app/.env
  
  docker:
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      sh -c "docker image prune -f && docker volume prune -f"
